[project]
name = "hr-policy-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "numpy>=2.4.6",
    "pdfplumber>=0.11.10",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "streamlit>=1.61.1",
    "uvicorn>=0.52.1",
]
